### ISSUE TITLE
Milestone for release 1.0

### ISSUE THREAD

**Issue by xelatihy** [xelatihy/yocto-gl#290]
Yocto/GL is getting close to release 1.0. To make the release helpful we should

- [x] it is probably best to use only issue and not milestone/projects to keep the ui simpler
- [x] tag all current issues with either the milestone or postponed
- [x] maybe remove all non-1.0 issues to remove noise
- [x] add everything that should either be consider for 1.0 or postponed
- [ ] fir each item where a decision needs to be made, add an issue for that desicion

one this is all done

- [ ] resolve all decisions and outstanding issue and release

**Comment by xelatihy** [comment]
Right now, everything is decide. We do not this anymore,
